# Старый вариант + тесты 
version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    container_name: foodgram-back
    build: backend/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - static:/app/staticfiles
      - media:/app/media
      # - static:/app/static/
      # - static_backend:/app/static/
    restart: unless-stopped

  frontend:
    container_name: foodgram-front
    build: frontend/
    volumes:
      # - static_frontend:/app/static/
      # - static:/app/result_build/
      - ./frontend:/app
      - ./frontend/build:/app/result_build
      # - static:/app/static/
      # - frontend_build:/app/result_build
    depends_on:
      - backend
    # command: sh -c "npm install && npm run build && cp -r build/* result_build/"
    # restart: "no"

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - media:/media
      - static:/static
      # # - static:/usr/share/nginx/html/
      # - static:/usr/share/nginx/html/
      # - media:/usr/share/nginx/media/
      # # - static_frontend:/usr/share/nginx/html/
      # # - static_backend:/usr/share/nginx/html/static_backend/
      # # - media:/usr/share/nginx/html/media/
      # # - ./docs/:/usr/share/nginx/html/api/docs/
      # # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
