# Generated by Django 5.2.4 on 2025-08-16 14:38

import apps.core.services
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='обновлено')),
                ('name', models.CharField(help_text='Единица измерения (г, мл, шт и т.д.).', max_length=64, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'единицы измерения',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': '%(app_label)s_%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='обновлено')),
                ('name', models.CharField(help_text='Название рецепта (до 256 символов)', max_length=256, verbose_name='название')),
                ('text', models.TextField(help_text='Описание рецепта', verbose_name='описание')),
                ('image', models.ImageField(help_text='Фотография готового блюда', upload_to=apps.core.services.get_upload_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png'), 'Недопустимое расширение файла. Разрешены: jpg, jpeg, png'), apps.core.validators.validate_safe_filename, apps.core.validators.validate_file_size], verbose_name='фото')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'Минимальное время: 1 мин'), django.core.validators.MaxValueValidator(720, 'Максимальное время: 720 мин')], verbose_name='время приготовления')),
                ('short_code', models.CharField(blank=True, editable=False, help_text='Уникальная последовательность', max_length=8, unique=True, verbose_name='уникальный код')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
                'default_related_name': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='обновлено')),
                ('amount', models.PositiveSmallIntegerField(help_text='Количество ингридиентов в рецепте', validators=[django.core.validators.MinValueValidator(1, 'Количество должно быть больше 1.'), django.core.validators.MaxValueValidator(1000, 'Максимальное количество: 1000')], verbose_name='количество')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
                'ordering': ('amount',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='обновлено')),
                ('name', models.CharField(help_text='Уникальное название тега для рецептов.', max_length=32, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, help_text='Уникальный URL-дружественный идентификатор тега.', max_length=32, unique=True, verbose_name='идентификатор')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='обновлено')),
                ('name', models.CharField(help_text='Название ингредиента (до 128 символов)', max_length=128, validators=[django.core.validators.MinLengthValidator(3, message='Название ингредиента должно содержать минимум 3 символа(ов).')], verbose_name='название')),
                ('measurement_unit', models.ForeignKey(help_text='Выберите единицу измерения для ингредиента.', on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipes.measurementunit', verbose_name='ед. изм.')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': '%(app_label)s_%(class)s',
            },
        ),
    ]
