# Generated by Django 5.2.4 on 2025-07-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингредиенты рецепта', through='recipes.RecipeIngredient', through_fields=('recipe', 'ingredient'), to='recipes.ingredient', verbose_name='ингредиенты'),
        ),
    ]
