# Generated by Django 5.2.4 on 2025-08-15 14:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_name_author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'Минимальное время: 1 мин'), django.core.validators.MaxValueValidator(720, 'Максимальное время: 720 мин')], verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Количество ингридиентов в рецепте', validators=[django.core.validators.MinValueValidator(1, 'Количество должно быть больше 1.'), django.core.validators.MaxValueValidator(1000, 'Максимальное количество: 1000')], verbose_name='количество'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='recipe_unique_name_author'),
        ),
    ]
