# Generated by Django 5.2.4 on 2025-08-03 23:09

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Фотография готового блюда', upload_to='recipes_test', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png'), 'Недопустимое расширение файла. Разрешены: jpg, jpeg, png'), apps.core.validators.validate_safe_filename, apps.core.validators.validate_file_size], verbose_name='фото'),
        ),
    ]
