# Generated by Django 5.2.4 on 2025-08-04 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(help_text='Количество ингридиентов в рецепте', validators=[django.core.validators.MinValueValidator(1, 'Количество должно быть больше 1.'), django.core.validators.MaxValueValidator(100, 'Максимальное количество: 100')], verbose_name='количество'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
