# Generated by Django 4.2.23 on 2025-07-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
                'default_related_name': '%(app_label)s_%(class)s',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='обновлено')),
                ('cart', models.ForeignKey(help_text='Корзина, к которой относится этот элемент.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='корзина')),
            ],
            options={
                'verbose_name': 'элемент корзины',
                'verbose_name_plural': 'элементы корзины',
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
                'default_related_name': '%(app_label)s_%(class)s',
            },
        ),
    ]
