# Generated by Django 4.2.23 on 2025-07-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, добавленный в корзину.', on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
