# Generated by Django 5.2.4 on 2025-07-30 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию (только буквы кириллицы или латиницы).', max_length=150, validators=[django.core.validators.MinLengthValidator(4, message='Фамилия не может быть короче {LAST_NAME_MIN_LENGTH} символов(а)'), django.core.validators.RegexValidator(message='Допускаются только буквы кириллицы или латиницы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Фамилия'),
        ),
    ]
