# Generated by Django 5.2.4 on 2025-08-01 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Введите фамилию (только буквы кириллицы или латиницы).', max_length=150, validators=[django.core.validators.MinLengthValidator(4, message='Фамилия не может быть короче {LAST_NAME_MIN_LENGTH} символов(а)'), django.core.validators.RegexValidator(message='Допускаются только буквы кириллицы или латиницы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Фамилия'),
        ),
    ]
