# Generated by Django 5.2.4 on 2025-08-01 18:35

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите фото в формате jpg, jpeg, png. Максимальный размер: 5МБ.', upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png'), 'Недопустимое расширение файла. Разрешены: jpg, jpeg, png'), apps.core.validators.validate_safe_filename, apps.core.validators.validate_file_size], verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=1, help_text='Введите фамилию (только буквы кириллицы или латиницы).', max_length=150, validators=[django.core.validators.MinLengthValidator(4, message='Фамилия не может быть короче {LAST_NAME_MIN_LENGTH} символов(а)'), django.core.validators.RegexValidator(message='Допускаются только буквы кириллицы или латиницы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
