# Generated by Django 5.2.4 on 2025-08-01 18:35

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_avatar_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите фото в формате jpg, jpeg, png. Максимальный размер: 5МБ.', null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png'), 'Недопустимое расширение файла. Разрешены: jpg, jpeg, png'), apps.core.validators.validate_safe_filename, apps.core.validators.validate_file_size], verbose_name='аватар'),
        ),
    ]
