RECIPE_NAME_MAX_LENGTH = 256
MIN_COOK_TIME = 1  # мин
MAX_COOK_TIME = 60 * 12  # час
TAG_NAME_MAX_LENGTH = TAG_SLUG_MAX_LENGTH = 32
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_NAME_MIN_LENGTH = 3
MEASUREMENTUNIT_MAX_NAME_LENGTH = 64

TEXT_TRUNCATE_LENGTH = 30 # Количество символов для усечения.
TEXT_TRUNCATE_SUFFIX = '..'

MAX_ATTEMPTS = 1000  # Для генерации slug
ALLOWED_EXTENSIONS = ('jpg', 'jpeg', 'png')
DEFAULT_EXT = 'jpg'
MAX_SIZE_FILE = 5  # MB

ARCHIVE_ROOT = 'archive'
UUID_FILENAME_LENGTH = 10
