name: CI/CD for foodgram with GitHub Actions

on: push

jobs:
  ruff:
    name: Ruff linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      -
        name: Check out code
        uses: actions/checkout@v4
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Display Python version
        run: python -c "imports sys; print(sys.version)"
      -
        name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.12.8
          pip install -r requirements/prod.txt
      -
        name: Run Ruff
        run: ruff check .

  flake8:
    name: flake linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: foodgram
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      -
        name: Check out code
        uses: actions/checkout@v4
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Display Python version
        run: python -c "imports sys; print(sys.version)"
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.3.0 flake8-isort==6.1.2
          pip install -r requirements/prod.txt

  # test:
  #   name: Backend tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.10", "3.11", "3.12"]
  #   services:
  #     postgres:
  #       image: postgres:13.10
  #       env:
  #         POSTGRES_USER: foodgram
  #         POSTGRES_PASSWORD: password
  #         POSTGRES_DB: db
  #       ports:
  #         - 5432:5432
  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  #   steps:
  #     -
  #       name: Check out code
  #       uses: actions/checkout@v4
  #     -
  #       name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     -
  #       name: Display Python version
  #       uses: python -c "imports sys; print(sys.version)"
  #     -
  #       name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install flake8
